/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControlHabitacion;
import Modelo.ConsultasHabitacion;
import Modelo.Habitacion;

/**
 *
 * @author Orel Aguilar
 */
public class Habitaciones extends javax.swing.JFrame {

    public Habitaciones() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        rsscalelabel.RSScaleLabel.setScaleLabel(fondoHabitacion, "src/habitacion.jpg");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnEntrarHab = new javax.swing.JButton();
        btnHabABienv = new javax.swing.JButton();
        fondoHabitacion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 65)); // NOI18N
        jLabel1.setText("Habitaciones");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 450, 70));

        btnEntrarHab.setText("Entrar");
        btnEntrarHab.setToolTipText("");
        btnEntrarHab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarHabActionPerformed(evt);
            }
        });
        getContentPane().add(btnEntrarHab, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 220, 80));

        btnHabABienv.setText("Inicio");
        btnHabABienv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHabABienvActionPerformed(evt);
            }
        });
        getContentPane().add(btnHabABienv, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 560, 90, -1));

        fondoHabitacion.setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().add(fondoHabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntrarHabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarHabActionPerformed
        // TODO add your handling code here:
        Habitacion hab = new Habitacion();
        ConsultasHabitacion cons_hab = new ConsultasHabitacion();
        FormHabitaciones habitacion = new FormHabitaciones();
        ControlHabitacion control = new ControlHabitacion(hab, cons_hab, habitacion); 
        control.iniciar();
        habitacion.setVisible(true);
        habitacion.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btnEntrarHabActionPerformed

    private void btnHabABienvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHabABienvActionPerformed
        // TODO add your handling code here:

        Bienvenido habABienv = new Bienvenido();
        habABienv.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnHabABienvActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrarHab;
    private javax.swing.JButton btnHabABienv;
    private javax.swing.JLabel fondoHabitacion;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
