/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControlReservacion;
import Modelo.ConsultasReservacion;
import Modelo.Reserva;

/**
 *
 * @author Orel Aguilar
 */
public class Reservas extends javax.swing.JFrame {

    /**
     * Creates new form Reservas
     */
    public Reservas() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        rsscalelabel.RSScaleLabel.setScaleLabel(fondoReservas, "src/Fondo.jpg");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnEntrarRes = new javax.swing.JButton();
        btnResABienv = new javax.swing.JButton();
        fondoReservas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 65)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("RESERVAS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 400, 130));

        btnEntrarRes.setText("Entrar");
        btnEntrarRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarResActionPerformed(evt);
            }
        });
        getContentPane().add(btnEntrarRes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 220, 80));

        btnResABienv.setText("Inicio");
        btnResABienv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResABienvActionPerformed(evt);
            }
        });
        getContentPane().add(btnResABienv, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 560, 90, -1));
        getContentPane().add(fondoReservas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntrarResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarResActionPerformed
        Reserva res = new Reserva();
        ConsultasReservacion consres = new ConsultasReservacion();
        FormReservas formres= new FormReservas();
        ControlReservacion controlres = new ControlReservacion(res, consres, formres); //Solo llama al frame que se va a usar
        controlres.iniciar();
        formres.setVisible(true);
        formres.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btnEntrarResActionPerformed

    private void btnResABienvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResABienvActionPerformed
        // TODO add your handling code here:
        Bienvenido resABienv = new Bienvenido();
        resABienv.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnResABienvActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reservas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrarRes;
    private javax.swing.JButton btnResABienv;
    private javax.swing.JLabel fondoReservas;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
